def dag_locale_pt_br() -> dict[str, str]:
    return {
        # Set Filter
        "selectAll": "(Selecionar todos)",
        "selectAllSearchResults": "(Selecionar todos os resultados da pesquisa)",
        "addCurrentSelectionToFilter": "Adicionar seleção atual ao filtro",
        "searchOoo": "Buscar...",
        "blanks": "(Vazios)",
        "noMatches": "Sem correspondências",
        # Number Filter & Text Filter
        "filterOoo": "Filtrar...",
        "equals": "Igual a",
        "notEqual": "Diferente de",
        "blank": "Vazio",
        "notBlank": "Não está vazio",
        "empty": "Escolha uma",
        # Number Filter
        "lessThan": "Menor que",
        "greaterThan": "Maior que",
        "lessThanOrEqual": "Menor ou igual a",
        "greaterThanOrEqual": "Maior ou igual a",
        "inRange": "Entre",
        "inRangeStart": "De",
        "inRangeEnd": "Até",
        # Text Filter
        "contains": "Contém",
        "notContains": "Não contém",
        "startsWith": "Começa com",
        "endsWith": "Termina com",
        # Date Filter
        "dateFormatOoo": "dd-mm-yyyy",
        "before": "Antes",
        "after": "Depois",
        # Filter Conditions
        "andCondition": "E",
        "orCondition": "OU",
        # Filter Buttons
        "applyFilter": "Aplicar",
        "resetFilter": "Redefinir",
        "clearFilter": "Limpar",
        "cancelFilter": "Cancelar",
        # Filter Titles
        "textFilter": "Filtro de Texto",
        "numberFilter": "Filtro Numérico",
        "dateFilter": "Filtro de Data",
        "setFilter": "Definir Filtro",
        # Group Column Filter
        "groupFilterSelect": "Selecionar campo:",
        # Advanced Filter
        "advancedFilterContains": "contém",
        "advancedFilterNotContains": "não contém",
        "advancedFilterTextEquals": "igual a",
        "advancedFilterTextNotEqual": "diferente de",
        "advancedFilterStartsWith": "começa com",
        "advancedFilterEndsWith": "termina com",
        "advancedFilterBlank": "está vazio",
        "advancedFilterNotBlank": "não está vazio",
        "advancedFilterEquals": "=",
        "advancedFilterNotEqual": "!=",
        "advancedFilterGreaterThan": ">",
        "advancedFilterGreaterThanOrEqual": ">=",
        "advancedFilterLessThan": "<",
        "advancedFilterLessThanOrEqual": "<=",
        "advancedFilterTrue": "é verdadeiro",
        "advancedFilterFalse": "é falso",
        "advancedFilterAnd": "E",
        "advancedFilterOr": "OU",
        "advancedFilterApply": "Aplicar",
        "advancedFilterBuilder": "Construtor",
        "advancedFilterValidationMissingColumn": "Coluna ausente",
        "advancedFilterValidationMissingOption": "Opção ausente",
        "advancedFilterValidationMissingValue": "Valor ausente",
        "advancedFilterValidationInvalidColumn": "Coluna não encontrada",
        "advancedFilterValidationInvalidOption": "Opção não encontrada",
        "advancedFilterValidationMissingQuote": "Falta uma aspa no valor",
        "advancedFilterValidationNotANumber": "Valor não é um número",
        "advancedFilterValidationInvalidDate": "Valor não é uma data válida",
        "advancedFilterValidationMissingCondition": "Falta uma condição",
        "advancedFilterValidationJoinOperatorMismatch": "Operadores de junção dentro de uma condição devem ser os mesmos",
        "advancedFilterValidationInvalidJoinOperator": "Operador de junção não encontrado",
        "advancedFilterValidationMissingEndBracket": "Falta um colchete de fechamento",
        "advancedFilterValidationExtraEndBracket": "Colchetes de fechamento em excesso",
        "advancedFilterValidationMessage": "Expressão contém um erro. ${variable} - ${variable}.",
        "advancedFilterValidationMessageAtEnd": "Expressão contém um erro. ${variable} no final da expressão.",
        "advancedFilterBuilderTitle": "Filtro Avançado",
        "advancedFilterBuilderApply": "Aplicar",
        "advancedFilterBuilderCancel": "Cancelar",
        "advancedFilterBuilderAddButtonTooltip": "Adicionar Filtro ou Grupo",
        "advancedFilterBuilderRemoveButtonTooltip": "Remover",
        "advancedFilterBuilderMoveUpButtonTooltip": "Mover para Cima",
        "advancedFilterBuilderMoveDownButtonTooltip": "Mover para Baixo",
        "advancedFilterBuilderAddJoin": "Adicionar Grupo",
        "advancedFilterBuilderAddCondition": "Adicionar Filtro",
        "advancedFilterBuilderSelectColumn": "Selecionar uma coluna",
        "advancedFilterBuilderSelectOption": "Selecionar uma opção",
        "advancedFilterBuilderEnterValue": "Insira um valor...",
        "advancedFilterBuilderValidationAlreadyApplied": "Filtro atual já aplicado.",
        "advancedFilterBuilderValidationIncomplete": "Nem todas as condições estão completas.",
        "advancedFilterBuilderValidationSelectColumn": "É necessário selecionar uma coluna.",
        "advancedFilterBuilderValidationSelectOption": "É necessário selecionar uma opção.",
        "advancedFilterBuilderValidationEnterValue": "É necessário inserir um valor.",
        # Side Bar
        "columns": "Colunas",
        "filters": "Filtros",
        # Columns Tool Panel
        "pivotMode": "Modo de Pivot",
        "groups": "Grupos de Linhas",
        "rowGroupColumnsEmptyMessage": "Arraste aqui para definir grupos de linhas",
        "values": "Valores",
        "valueColumnsEmptyMessage": "Arraste aqui para agregar",
        "pivots": "Rótulos de Colunas",
        "pivotColumnsEmptyMessage": "Arraste aqui para definir rótulos de colunas",
        # Header of the Default Group Column
        "group": "Grupo",
        # Row Drag
        "rowDragRow": "linha",
        "rowDragRows": "linhas",
        # Other
        "loadingOoo": "Carregando...",
        "loadingError": "ERR",
        "noRowsToShow": "Sem linhas para exibir",
        "enabled": "Habilitado",
        # Menu
        "pinColumn": "Fixar Coluna",
        "pinLeft": "Fixar à Esquerda",
        "pinRight": "Fixar à Direita",
        "noPin": "Não Fixar",
        "valueAggregation": "Agregação de Valor",
        "noAggregation": "Nenhum",
        "autosizeThiscolumn": "Ajustar Largura Desta Coluna",
        "autosizeAllColumns": "Ajustar Largura de Todas as Colunas",
        "groupBy": "Agrupar por",
        "ungroupBy": "Desagrupar por",
        "ungroupAll": "Desagrupar Tudo",
        "addToValues": "Adicionar ${variable} aos valores",
        "removeFromValues": "Remover ${variable} dos valores",
        "addToLabels": "Adicionar ${variable} aos rótulos",
        "removeFromLabels": "Remover ${variable} dos rótulos",
        "resetColumns": "Redefinir Colunas",
        "expandAll": "Expandir Todos os Grupos de Linhas",
        "collapseAll": "Fechar Todos os Grupos de Linhas",
        "copy": "Copiar",
        "ctrlC": "Ctrl+C",
        "ctrlX": "Ctrl+X",
        "copyWithHeaders": "Copiar com Cabeçalhos",
        "copyWithGroupHeaders": "Copiar com Cabeçalhos de Grupo",
        "cut": "Cortar",
        "paste": "Colar",
        "ctrlV": "Ctrl+V",
        "export": "Exportar",
        "csvExport": "Exportar para CSV",
        "excelExport": "Exportar para Excel",
        "columnFilter": "Filtro de Coluna",
        "columnChooser": "Escolher Colunas",
        "sortAscending": "Ordenar Crescente",
        "sortDescending": "Ordenar Decrescente",
        "sortUnSort": "Limpar Ordenação",
        # Enterprise Menu Aggregation and Status Bar
        "sum": "Soma",
        "first": "Primeiro",
        "last": "Último",
        "min": "Mínimo",
        "max": "Máximo",
        "none": "Nenhum",
        "count": "Contagem",
        "avg": "Média",
        "filteredRows": "Filtradas",
        "selectedRows": "Selecionadas",
        "totalRows": "Total de Linhas",
        "totalAndFilteredRows": "Linhas",
        "more": "Mais",
        "to": "até",
        "of": "de",
        "page": "Página",
        "pageLastRowUnknown": "?",
        "nextPage": "Próxima Página",
        "lastPage": "Última Página",
        "firstPage": "Primeira Página",
        "previousPage": "Página Anterior",
        "pageSizeSelectorLabel": "Tamanho da Página:",
        "footerTotal": "Total",
        # Pivoting
        "pivotColumnGroupTotals": "Total",
        # Enterprise Menu (Charts)
        "pivotChartAndPivotMode": "Gráfico de Pivot & Modo de Pivot",
        "pivotChart": "Gráfico de Pivot",
        "chartRange": "Intervalo do Gráfico",
        "columnChart": "Coluna",
        "groupedColumn": "Agrupado",
        "stackedColumn": "Empilhado",
        "normalizedColumn": r"100% Empilhado",
        "barChart": "Barra",
        "groupedBar": "Agrupado",
        "stackedBar": "Empilhado",
        "normalizedBar": r"100% Empilhado",
        "pieChart": "Pizza",
        "pie": "Pizza",
        "donut": "Rosca",
        "line": "Linha",
        "xyChart": "X Y (Dispersão)",
        "scatter": "Dispersão",
        "bubble": "Bolha",
        "areaChart": "Área",
        "area": "Área",
        "stackedArea": "Empilhada",
        "normalizedArea": r"100% Empilhada",
        "histogramChart": "Histograma",
        "histogramFrequency": "Frequência",
        "polarChart": "Polar",
        "radarLine": "Linha de Radar",
        "radarArea": "Área de Radar",
        "nightingale": "Nightingale",
        "radialColumn": "Coluna Radial",
        "radialBar": "Barra Radial",
        # Statistical Charts
        "statisticalChart": "Estatístico",
        "boxPlot": "Gráfico de Caixa",
        "rangeBar": "Barra de Intervalo",
        "rangeArea": "Área de Intervalo",
        # Hierarchical Charts
        "hierarchicalChart": "Hierárquico",
        "treemap": "Mapa de Árvore",
        "sunburst": "Explosão Solar",
        # Specialized Charts
        "specializedChart": "Especializado",
        "waterfall": "Cascata",
        "heatmap": "Mapa de Calor",
        # Combination Charts
        "combinationChart": "Combinação",
        "columnLineCombo": "Coluna & Linha",
        "AreaColumnCombo": "Área & Coluna",
        # Charts
        "pivotChartTitle": "Gráfico de Pivot",
        "rangeChartTitle": "Gráfico de Intervalo",
        "settings": "Configurações",
        "data": "Dados",
        "format": "Formato",
        "categories": "Categorias",
        "defaultCategory": "(Nenhum)",
        "series": "Séries",
        "switchCategorySeries": "Alternar Categoria / Série",
        "categoryValues": "Valores de Categoria",
        "seriesLabels": "Rótulos de Série",
        "aggregate": "Agregado",
        "xyValues": "Valores X Y",
        "paired": "Modo Pareado",
        "axis": "Eixo",
        "xAxis": "Eixo Horizontal",
        "yAxis": "Eixo Vertical",
        "polarAxis": "Eixo Polar",
        "radiusAxis": "Eixo de Raio",
        "navigator": "Navegador",
        "zoom": "Zoom",
        "animation": "Animação",
        "crosshair": "Mira",
        "color": "Cor",
        "thickness": "Espessura",
        "preferredLength": "Comprimento Preferido",
        "xType": "Tipo X",
        "axisType": "Tipo de Eixo",
        "automatic": "Automático",
        "category": "Categoria",
        "number": "Número",
        "time": "Tempo",
        "timeFormat": "Formato de Tempo",
        "autoRotate": "Rotação Automática",
        "labelRotation": "Rotação",
        "circle": "Círculo",
        "polygon": "Polígono",
        "orientation": "Orientação",
        "fixed": "Fixo",
        "parallel": "Paralelo",
        "perpendicular": "Perpendicular",
        "radiusAxisPosition": "Posição",
        "ticks": "Marcas",
        "gridLines": "Linhas de Grade",
        "width": "Largura",
        "height": "Altura",
        "length": "Comprimento",
        "padding": "Preenchimento",
        "spacing": "Espaçamento",
        "chart": "Gráfico",
        "title": "Título",
        "titlePlaceholder": "Título do gráfico - clique duas vezes para editar",
        "background": "Fundo",
        "font": "Fonte",
        "top": "Superior",
        "right": "Direita",
        "bottom": "Inferior",
        "left": "Esquerda",
        "labels": "Rótulos",
        "calloutLabels": "Rótulos de Anotação",
        "sectorLabels": "Rótulos de Setor",
        "positionRatio": "Proporção de Posição",
        "size": "Tamanho",
        "shape": "Forma",
        "minSize": "Tamanho Mínimo",
        "maxSize": "Tamanho Máximo",
        "legend": "Legenda",
        "position": "Posição",
        "markerSize": "Tamanho do Marcador",
        "markerStroke": "Traço do Marcador",
        "markerPadding": "Preenchimento do Marcador",
        "itemSpacing": "Espaçamento de Item",
        "itemPaddingX": "Preenchimento X do Item",
        "itemPaddingY": "Preenchimento Y do Item",
        "layoutHorizontalSpacing": "Espaçamento Horizontal",
        "layoutVerticalSpacing": "Espaçamento Vertical",
        "strokeWidth": "Largura do Traço",
        "offset": "Deslocamento",
        "offsets": "Deslocamentos",
        "tooltips": "Dicas de Ferramenta",
        "callout": "Anotação",
        "markers": "Marcadores",
        "shadow": "Sombra",
        "blur": "Desfoque",
        "xOffset": "Deslocamento X",
        "yOffset": "Deslocamento Y",
        "lineWidth": "Largura da Linha",
        "lineDash": "Tracejado da Linha",
        "lineDashOffset": "Deslocamento do Tracejado",
        "scrollingZoom": "Rolagem",
        "scrollingStep": "Passo de Rolagem",
        "selectingZoom": "Selecionando",
        "durationMillis": "Duração (ms)",
        "crosshairLabel": "Rótulo",
        "crosshairSnap": "Ajustar ao Nó",
        "normal": "Normal",
        "bold": "Negrito",
        "italic": "Itálico",
        "boldItalic": "Negrito e Itálico",
        "predefined": "Predefinido",
        "fillOpacity": "Opacidade do Preenchimento",
        "strokeColor": "Cor da Linha",
        "strokeOpacity": "Opacidade da Linha",
        "miniChart": "Mini-Gráfico",
        "histogramBinCount": "Contagem de Classes",
        "connectorLine": "Linha de Conexão",
        "seriesItems": "Itens de Série",
        "seriesItemType": "Tipo de Item",
        "seriesItemPositive": "Positivo",
        "seriesItemNegative": "Negativo",
        "seriesItemLabels": "Rótulos de Item",
        # Chart Groups
        "columnGroup": "Coluna",
        "barGroup": "Barra",
        "pieGroup": "Pizza",
        "lineGroup": "Linha",
        "scatterGroup": "X Y (Dispersão)",
        "areaGroup": "Área",
        "polarGroup": "Polar",
        "statisticalGroup": "Estatístico",
        "hierarchicalGroup": "Hierárquico",
        "specializedGroup": "Especializado",
        "combinationGroup": "Combinação",
        # Tooltips
        "groupedColumnTooltip": "Agrupado",
        "stackedColumnTooltip": "Empilhado",
        "normalizedColumnTooltip": r"100% Empilhado",
        "groupedBarTooltip": "Agrupado",
        "stackedBarTooltip": "Empilhado",
        "normalizedBarTooltip": r"100% Empilhado",
        "pieTooltip": "Pizza",
        "donutTooltip": "Rosquinha",
        "lineTooltip": "Linha",
        "groupedAreaTooltip": "Área",
        "stackedAreaTooltip": "Empilhado",
        "normalizedAreaTooltip": r"100% Empilhado",
        "scatterTooltip": "Dispersão",
        "bubbleTooltip": "Bolha",
        "histogramTooltip": "Histograma",
        "radialColumnTooltip": "Coluna Radial",
        "radialBarTooltip": "Barra Radial",
        "radarLineTooltip": "Linha de Radar",
        "radarAreaTooltip": "Área de Radar",
        "nightingaleTooltip": "Nightingale",
        "rangeBarTooltip": "Barra de Intervalo",
        "rangeAreaTooltip": "Área de Intervalo",
        "boxPlotTooltip": "Gráfico de Caixa",
        "treemapTooltip": "Mapa de Árvore",
        "sunburstTooltip": "Explosão Solar",
        "waterfallTooltip": "Cascata",
        "heatmapTooltip": "Mapa de Calor",
        "columnLineComboTooltip": "Coluna & Linha",
        "areaColumnComboTooltip": "Área & Coluna",
        "customComboTooltip": "Combinação Personalizada",
        # Chart Settings
        "innerRadius": "Raio Interno",
        "startAngle": "Ângulo Inicial",
        "endAngle": "Ângulo Final",
        "reverseDirection": "Inverter Direção",
        "groupPadding": "Preenchimento do Grupo",
        "seriesPadding": "Preenchimento da Série",
        "tile": "Bloco",
        "whisker": "Bigode",
        "cap": "Tampa",
        "capLengthRatio": "Proporção do Comprimento",
        "labelPlacement": "Posicionamento",
        "inside": "Dentro",
        "outside": "Fora",
        "noDataToChart": "Nenhum dado disponível para ser exibido.",
        "pivotChartRequiresPivotMode": "O Gráfico de Pivot requer o Modo de Pivot ativado.",
        "chartSettingsToolbarTooltip": "Menu",
        "chartLinkToolbarTooltip": "Vinculado à Grade",
        "chartUnlinkToolbarTooltip": "Desvinculado da Grade",
        "chartDownloadToolbarTooltip": "Baixar Gráfico",
        "chartEdit": "Editar Gráfico",
        "chartAdvancedSettings": "Configurações Avançadas",
        "chartLink": "Vincular à Grade",
        "chartUnlink": "Desvincular da Grade",
        "chartDownload": "Baixar Gráfico",
        "seriesChartType": "Tipo de Gráfico da Série",
        "seriesType": "Tipo de Série",
        "secondaryAxis": "Eixo Secundário",
        "seriesAdd": "Adicionar uma série",
        "categoryAdd": "Adicionar uma categoria",
        "advancedSettings": "Configurações Avançadas",
        # ARIA
        "ariaAdvancedFilterBuilderItem": "${variable}. Nível ${variable}. Pressione ENTER para editar.",
        "ariaAdvancedFilterBuilderItemValidation": "${variable}. Nível ${variable}. ${variable} Pressione ENTER para editar.",
        "ariaAdvancedFilterBuilderList": "Lista do Construtor de Filtro Avançado",
        "ariaAdvancedFilterBuilderFilterItem": "Condição de Filtro",
        "ariaAdvancedFilterBuilderGroupItem": "Grupo de Filtro",
        "ariaAdvancedFilterBuilderColumn": "Coluna",
        "ariaAdvancedFilterBuilderOption": "Opção",
        "ariaAdvancedFilterBuilderValueP": "Valor",
        "ariaAdvancedFilterBuilderJoinOperator": "Operador de Junção",
        "ariaAdvancedFilterInput": "Entrada de Filtro Avançado",
        "ariaChecked": "marcado",
        "ariaColumn": "Coluna",
        "ariaColumnGroup": "Grupo de Colunas",
        "ariaColumnFiltered": "Coluna Filtrada",
        "ariaColumnSelectAll": "Alternar Seleção de Todas as Colunas",
        "ariaDateFilterInput": "Entrada de Filtro de Data",
        "ariaDefaultListName": "Lista",
        "ariaFilterColumnsInput": "Entrada de Colunas de Filtro",
        "ariaFilterFromValue": "Filtrar a partir do valor",
        "ariaFilterInput": "Entrada de Filtro",
        "ariaFilterList": "Lista de Filtros",
        "ariaFilterToValue": "Filtrar até o valor",
        "ariaFilterValue": "Valor de Filtro",
        "ariaFilterMenuOpen": "Abrir Menu de Filtro",
        "ariaFilteringOperator": "Operador de Filtragem",
        "ariaHidden": "oculto",
        "ariaIndeterminate": "indeterminado",
        "ariaInputEditor": "Editor de Entrada",
        "ariaMenuColumn": "Pressione ALT DOWN para abrir o menu da coluna",
        "ariaFilterColumn": "Pressione CTRL ENTER para abrir o filtro",
        "ariaRowDeselect": "Pressione SPACE para desmarcar esta linha",
        "ariaRowSelectAll": "Pressione SPACE para alternar a seleção de todas as linhas",
        "ariaRowToggleSelection": "Pressione SPACE para alternar a seleção da linha",
        "ariaRowSelect": "Pressione SPACE para selecionar esta linha",
        "ariaRowSelectionDisabled": "A seleção de linha está desativada para esta linha",
        "ariaSearch": "Pesquisar",
        "ariaSortableColumn": "Pressione ENTER para ordenar",
        "ariaToggleVisibility": "Pressione SPACE para alternar a visibilidade",
        "ariaToggleCellValue": "Pressione SPACE para alternar o valor da célula",
        "ariaUnchecked": "desmarcado",
        "ariaVisible": "visível",
        "ariaSearchFilterValues": "Pesquisar valores de filtro",
        "ariaPageSizeSelectorLabel": "Tamanho da Página",
        "ariaChartMenuClose": "Fechar Menu de Edição de Gráfico",
        # ARIA Labels for Drop Zones
        "ariaRowGroupDropZonePanelLabel": "Grupos de Linha",
        "ariaValuesDropZonePanelLabel": "Valores",
        "ariaPivotDropZonePanelLabel": "Rótulos de Coluna",
        "ariaDropZoneColumnComponentDescription": "Pressione DELETE para remover",
        "ariaDropZoneColumnValueItemDescription": "Pressione ENTER para alterar o tipo de agregação",
        "ariaDropZoneColumnGroupItemDescription": "Pressione ENTER para ordenar",
        "ariaDropZoneColumnComponentAggFuncSeparator": " de ",
        "ariaDropZoneColumnComponentSortAscending": "ascendente",
        "ariaDropZoneColumnComponentSortDescending": "descendente",
        # ARIA Labels for Dialogs
        "ariaLabelColumnMenu": "Menu de Coluna",
        "ariaLabelColumnFilter": "Filtro de Coluna",
        "ariaLabelCellEditor": "Editor de Célula",
        "ariaLabelDialog": "Diálogo",
        "ariaLabelSelectField": "Campo de Seleção",
        "ariaLabelRichSelectField": "Campo de Seleção Avançada",
        "ariaLabelTooltip": "Tooltip",
        "ariaLabelContextMenu": "Menu de Contexto",
        "ariaLabelSubMenu": "Submenu",
        "ariaLabelAggregationFunction": "Função de Agregação",
        "ariaLabelAdvancedFilterAutocomplete": "Autocompletar Filtro Avançado",
        "ariaLabelAdvancedFilterBuilderAddField": "Adicionar Campo ao Construtor de Filtro Avançado",
        "ariaLabelAdvancedFilterBuilderColumnSelectField": "Campo de Seleção de Coluna no Construtor de Filtro Avançado",
        "ariaLabelAdvancedFilterBuilderOptionSelectField": "Campo de Seleção de Opção no Construtor de Filtro Avançado",
        "ariaLabelAdvancedFilterBuilderJoinSelectField": "Campo de Seleção de Operador de Junção no Construtor de Filtro Avançado",
        # ARIA Labels for the Side Bar
        "ariaColumnPanelList": "Lista de Colunas",
        "ariaFilterPanelList": "Lista de Filtros",
        # Number Format (Status Bar, Pagination Panel)
        "thousandSeparator": ",",
        "decimalSeparator": ".",
        # Data types
        "true": "Verdadeiro",
        "false": "Falso",
        "invalidDate": "Data Inválida",
        "invalidNumber": "Número Inválido",
        "january": "Janeiro",
        "february": "Fevereiro",
        "march": "Março",
        "april": "Abril",
        "may": "Maio",
        "june": "Junho",
        "july": "Julho",
        "august": "Agosto",
        "september": "Setembro",
        "october": "Outubro",
        "november": "Novembro",
        "december": "Dezembro",
        # Time formats
        "timeFormatSlashesDDMMYYYY": "DD/MM/YYYY",
        "timeFormatSlashesMMDDYYYY": "MM/DD/YYYY",
        "timeFormatSlashesDDMMYY": "DD/MM/YY",
        "timeFormatSlashesMMDDYY": "MM/DD/YY",
        "timeFormatDotsDDMYY": "DD.M.YY",
        "timeFormatDotsMDDYY": "M.DD.YY",
        "timeFormatDashesYYYYMMDD": "YYYY-MM-DD",
        "timeFormatSpacesDDMMMMYYYY": "DD MMMM YYYY",
        "timeFormatHHMMSS": "HH:MM:SS",
        "timeFormatHHMMSSAmPm": "HH:MM:SS AM/PM",
    }
